name: test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: tests with go1.15
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: print go version
        run: go version
      - name: run unit test
        run: go test -race -v
